### ISSUE TITLE
Image size has increased significantly over versions

### ISSUE THREAD

**Issue by nuwang** [CloudVE/galaxy-kube-playbook#19]
It seems that the minimal container images's size has been increasing over the past few Galaxy releases. These are the compressed sizes, so the uncompressed size is far more significant (e.g. in the latest build, there is a 400MB size increase, from 1.3GB to 1.7GB)

| Version | Size on DockerHub | Difference from previous |
|---------|-------------------|------------|
| 19.09     | 238.19 MB             | N/A              |
| 20.01     | 280.77 MB             | 42.58 MB   |
| 20.05     | 346.34 MB            | 65.57 MB   |
| 20.09     | 362.67 MB            | 16.33 MB   |
| 20.09.3  | 437.93 MB            | 75.26 MB   |

The cause is a significant increase in the `/galaxy` dir. The reason needs investigation.

@afgane @almahmoud @dannon @ic4f @mvdbeek

**Comment by dannon** [comment]
@nuwang I'll take a look.

**Comment by dannon** [comment]
Ok, I have a new build back at 248.78 MB (compressed on dockerhub), but it seems like it's not exactly clear where to push changes to the Dockerfile at the moment (given the open PR at https://github.com/galaxyproject/galaxy/pull/10681)

**Comment by nuwang** [comment]
@dannon That's great! I've restored the Dockerfile to its previous state, pending the outstanding PRs, so can you try it now?

**Comment by dannon** [comment]
@nuwang Sure, pushed it up here.  I'll push the same change to the corresponding Galaxy branch too.
