### ISSUE TITLE
Validation error for Settings - galaxy_user is required when running as root

### ISSUE THREAD

**Issue by EGI-ILM** [CloudVE/galaxy-kube-playbook#37]
Hi,

In the previous weeks I built the image correctly but just recently (and all of a sudden) I am getting the error below about the lack of a `galaxy_user`. I do not recall making any change in the files, but I do not see any changes in the relevant repositories either from the week it worked to the next one.

I intend to research the issue, but if you could please point me in the right direction I appreciate it, as it would save me some time.

Many thanks.

```
#0 284.1 fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/galaxy/server/.venv/bin/galaxyctl", "-c", "/galaxy/server/config/galaxy.yml", "update"], "delta": "0:00:01.492455", "end": "2023-04-19 15:25:32.492802", "msg": "non-zero return code", "rc": 1, "start": "2023-04-19 15:25:31.000347", "stderr": "Error: 1 validation error for Settings\ngalaxy_user\n  galaxy_user is required when running as root (type=value_error)", "stderr_lines": ["Error: 1 validation error for Settings", "galaxy_user", "  galaxy_user is required when running as root (type=value_error)"], "stdout": "", "stdout_lines": []}
#0 284.1
#0 284.1 PLAY RECAP *********************************************************************
#0 284.1 localhost                  : ok=34   changed=9    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0
#0 284.1
------
.k8s_ci.Dockerfile:75
--------------------
  73 |     ARG SERVER_DIR
  74 |
  75 | >>> RUN ansible-playbook -i localhost, playbook.yml -v -e "{galaxy_build_client: false}" -e galaxy_virtualenv_command=virtualenv
  76 |
  77 |     # Remove build artifacts + files not needed in container
--------------------
ERROR: failed to solve: process "/bin/sh -c ansible-playbook -i localhost, playbook.yml -v -e \"{galaxy_build_client: false}\" -e galaxy_virtualenv_command=virtualenv" did not complete successfully: exit code: 2
```

**Comment by afgane** [comment]
I can confirm I'm seeing the same issue. Don't know yet what's causing it though.

**Comment by afgane** [comment]
The above referenced commit fixes this in my tests. Let me know if that's not the case for you.

**Comment by EGI-ILM** [comment]
Thank you @afgane for your help!  Unfortunately, I am getting the same error. Unless the change is not applied to my command, but I can see that the change has been committed, so in theory I should run it as usual.

**Comment by nuwang** [comment]
@EGI-ILM Was `--no-cache` specified when building the docker image?

**Comment by EGI-ILM** [comment]
You are right, thanks!
I thought of that and discarded it because thought it did not affect, but with `no-cache` it worked!
